/** @deprecated Import from ./WelcomeUIKit instead. Re-exports preserve existing names. */
export {
  AppBrand,
  AppBrand as WelcomeBrand,
  CircleCluster,
  CircleCluster as WelcomeCommunityVisual,
  CenteredCard,
  WelcomePageShell,
  WelcomeHeadline,
  WelcomeTagline,
  WelcomeDescription,
  WelcomeReassurance,
  WelcomeActions,
  PrimaryButton,
  SecondaryButton,
  WelcomeTextAction,
  WelcomeBackLink,
  WelcomeDivider,
  FeatureRow,
  FeatureRow as WelcomeTrustList,
} from "./WelcomeUIKit";
